import type { Claim } from "./types";

const today = new Date();
function daysAgo(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function daysFromNow(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

export const MOCK_CLAIMS: Claim[] = [
  {
    id: "C-10042",
    mondayItemId: "1234567890",
    patientName: "Jane Smith",
    dob: "1970-01-10",
    dos: daysAgo(22),
    primaryPayor: "Fidelis Medicaid",
    insuranceType: "Medicaid HMO",
    memberId: "ABC123456",
    claimSentDate: daysAgo(20),
    primaryStatus: "Review",
    status277: "Payer Accepted",
    claimStatusCategory: "Paid",
    claimStatusDetail: "Finalized — payment made",
    lastClaimStatusCheck: daysAgo(5),
    claimId: "CLM-77881",
    payerClaimNumber: "FID2026-998877",
    estPay: 1245.5,
    primaryPaid: 900,
    prAmount: 145.5,
    rawEraDate: daysAgo(3),
    rawEraClaimStatus: "Processed as Primary",
    primaryPaidDate: daysAgo(3),
    secondaryPayer: "Medicare",
    denialAction: null,
    nextActionDate: null,
    transfer: "Not Started",
    subscriptionClearance: "Manager Review",
    claimsHoldReason: "Secondary outstanding",
    sourceSubscriptionItemId: "SUB-44210",
    sourceOrderItemId: "ORD-99812",
    activity: [
      { ts: daysAgo(20), actor: "system", message: "837 submitted to Stedi." },
      { ts: daysAgo(19), actor: "system", message: "277 Payer Accepted." },
      { ts: daysAgo(3), actor: "system", message: "835 ERA parsed — Primary set to Review." },
    ],
    lines: [
      {
        id: "L1", product: "Insulin Pump", hcpcs: "E0784", modifiers: ["NU"],
        units: 1, charge: 4500, estPay: 800, primaryPaid: 600, allowed: 700,
        deductible: 100, coinsurance: 0, copay: 0, patientResponsibility: 100,
        carc: ["45"], rarc: [], adjustmentReasons: ["Contractual adjustment"],
        remarkText: [], denialAnalysis: null,
        coAmount: 3800, prAmount: 100, oaAmount: 0, piAmount: 0,
      },
      {
        id: "L2", product: "Infusion Set", hcpcs: "A4230", modifiers: ["NU"],
        units: 10, charge: 350, estPay: 220, primaryPaid: 180, allowed: 220,
        deductible: 0, coinsurance: 40, copay: 0, patientResponsibility: 40,
        carc: ["45"], rarc: [], adjustmentReasons: ["Contractual adjustment"],
        remarkText: [], denialAnalysis: null,
        coAmount: 130, prAmount: 40, oaAmount: 0, piAmount: 0,
      },
      {
        id: "L3", product: "CGM Sensors", hcpcs: "A4239", modifiers: [],
        units: 4, charge: 600, estPay: 225.5, primaryPaid: 120, allowed: 225.5,
        deductible: 0, coinsurance: 5.5, copay: 0, patientResponsibility: 5.5,
        carc: ["151"], rarc: ["N362"], adjustmentReasons: ["Units exceed allowed"],
        remarkText: ["Number of days/units exceeds maximum allowed."],
        denialAnalysis: "Units / Frequency",
        coAmount: 374.5, prAmount: 5.5, oaAmount: 100, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10043",
    mondayItemId: "1234567891",
    patientName: "Robert Johnson",
    dob: "1965-08-22",
    dos: daysAgo(28),
    primaryPayor: "Aetna",
    insuranceType: "Commercial PPO",
    memberId: "AET998877",
    claimSentDate: daysAgo(24),
    primaryStatus: "Outstanding",
    status277: "Payer Accepted",
    claimStatusCategory: "In Process",
    claimStatusDetail: "Claim received, in adjudication",
    lastClaimStatusCheck: daysAgo(8),
    claimId: "CLM-77882",
    payerClaimNumber: "AET-44521",
    estPay: 980,
    primaryPaid: 0,
    prAmount: 0,
    rawEraDate: null,
    primaryPaidDate: null,
    denialAction: null,
    nextActionDate: null,
    lines: [
      {
        id: "L1", product: "CGM Monitor", hcpcs: "A4238", modifiers: ["NU"],
        units: 1, charge: 1200, estPay: 980, primaryPaid: 0, allowed: 0,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: [], rarc: [], adjustmentReasons: [], remarkText: [],
        denialAnalysis: null, coAmount: 0, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10044",
    mondayItemId: "1234567892",
    patientName: "Maria Gonzalez",
    dob: "1982-03-15",
    dos: daysAgo(40),
    primaryPayor: "United Healthcare",
    insuranceType: "Commercial",
    memberId: "UHC55443",
    claimSentDate: daysAgo(38),
    primaryStatus: "Denied (Or Partly)",
    status277: "Payer Accepted",
    claimStatusCategory: "Denied",
    claimStatusDetail: "Authorization not on file",
    lastClaimStatusCheck: daysAgo(2),
    claimId: "CLM-77883",
    payerClaimNumber: "UHC-9921",
    estPay: 850,
    primaryPaid: 0,
    prAmount: 0,
    rawEraDate: daysAgo(10),
    rawEraClaimStatus: "Denied",
    denialAction: null,
    actionContext: "",
    nextActionDate: daysAgo(2),
    lines: [
      {
        id: "L1", product: "Insulin Pump", hcpcs: "E0784", modifiers: ["NU"],
        units: 1, charge: 4500, estPay: 850, primaryPaid: 0, allowed: 0,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: ["197"], rarc: ["N575"], adjustmentReasons: ["Authorization missing"],
        remarkText: ["Precertification/authorization required."],
        denialAnalysis: "No Auth",
        coAmount: 4500, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10045",
    mondayItemId: "1234567893",
    patientName: "David Lee",
    dob: "1978-11-02",
    dos: daysAgo(10),
    primaryPayor: "Cigna",
    insuranceType: "Commercial PPO",
    memberId: "CIG12000",
    claimSentDate: daysAgo(8),
    primaryStatus: "Submitted",
    status277: "Stedi Accepted",
    claimStatusCategory: null,
    claimId: "CLM-77884",
    estPay: 540,
    primaryPaid: 0,
    prAmount: 0,
    rawEraDate: null,
    denialAction: null,
    nextActionDate: null,
    lines: [
      {
        id: "L1", product: "Cartridge", hcpcs: "A4232", modifiers: [],
        units: 10, charge: 540, estPay: 540, primaryPaid: 0, allowed: 0,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: [], rarc: [], adjustmentReasons: [], remarkText: [],
        denialAnalysis: null, coAmount: 0, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10046",
    mondayItemId: "1234567894",
    patientName: "Emily Carter",
    dob: "1991-05-30",
    dos: daysAgo(45),
    primaryPayor: "BCBS",
    insuranceType: "Commercial",
    memberId: "BCBS3344",
    claimSentDate: daysAgo(42),
    primaryStatus: "Outstanding",
    status277: "Payer Accepted",
    claimStatusCategory: "No Match",
    claimStatusDetail: "Payer cannot locate claim",
    lastClaimStatusCheck: daysAgo(1),
    claimId: "CLM-77885",
    estPay: 1100,
    primaryPaid: 0,
    prAmount: 0,
    rawEraDate: null,
    denialAction: "Investigate",
    actionContext: "Call BCBS to confirm receipt; verify payer ID.",
    nextActionDate: daysFromNow(2),
    lines: [
      {
        id: "L1", product: "Insulin Pump", hcpcs: "E0784", modifiers: ["NU"],
        units: 1, charge: 4500, estPay: 1100, primaryPaid: 0, allowed: 0,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: [], rarc: [], adjustmentReasons: [], remarkText: [],
        denialAnalysis: null, coAmount: 0, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10047",
    mondayItemId: "1234567895",
    patientName: "Thomas Nguyen",
    dob: "1958-09-19",
    dos: daysAgo(18),
    primaryPayor: "Medicare",
    insuranceType: "Medicare Part B",
    memberId: "1EG4-TE5-MK72",
    claimSentDate: daysAgo(17),
    primaryStatus: "Review",
    status277: "Payer Accepted",
    claimStatusCategory: "Denied",
    lastClaimStatusCheck: daysAgo(3),
    claimId: "CLM-77886",
    payerClaimNumber: "MCR-77110",
    estPay: 720,
    primaryPaid: 0,
    prAmount: 0,
    rawEraDate: daysAgo(2),
    rawEraClaimStatus: "Denied",
    primaryPaidDate: null,
    denialAction: null,
    secondaryPayer: "Medicaid",
    transfer: "Not Started",
    subscriptionClearance: "Hold",
    claimsHoldReason: "Denial / appeal pending",
    sourceSubscriptionItemId: "SUB-44310",
    sourceOrderItemId: "ORD-99815",
    activity: [
      { ts: daysAgo(2), actor: "system", message: "835 ERA parsed — full denial reported." },
    ],
    lines: [
      {
        id: "L1", product: "CGM Sensors", hcpcs: "A4239", modifiers: [],
        units: 3, charge: 450, estPay: 360, primaryPaid: 0, allowed: 0,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: ["197"], rarc: ["N575"], adjustmentReasons: ["Authorization missing"],
        remarkText: ["Precertification/authorization required."],
        denialAnalysis: "No Auth",
        coAmount: 450, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
      {
        id: "L2", product: "Infusion Set", hcpcs: "A4230", modifiers: [],
        units: 10, charge: 350, estPay: 360, primaryPaid: 0, allowed: 0,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: ["197"], rarc: ["N575"], adjustmentReasons: ["Authorization missing"],
        remarkText: ["Precertification/authorization required."],
        denialAnalysis: "No Auth",
        coAmount: 350, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10048",
    mondayItemId: "1234567896",
    patientName: "Sophia Patel",
    dob: "1986-07-12",
    dos: daysAgo(15),
    primaryPayor: "Aetna",
    insuranceType: "Commercial PPO",
    memberId: "AET771122",
    claimSentDate: daysAgo(13),
    primaryStatus: "Review",
    status277: "Payer Accepted",
    claimStatusCategory: "Paid",
    claimStatusDetail: "Finalized — payment made",
    lastClaimStatusCheck: daysAgo(2),
    claimId: "CLM-77887",
    payerClaimNumber: "AET-66230",
    estPay: 600,
    primaryPaid: 540,
    prAmount: 60,
    rawEraDate: daysAgo(1),
    rawEraClaimStatus: "Processed as Primary",
    primaryPaidDate: daysAgo(1),
    denialAction: null,
    transfer: "Not Started",
    subscriptionClearance: "Clear",
    claimsHoldReason: null,
    sourceSubscriptionItemId: "SUB-44410",
    sourceOrderItemId: "ORD-99820",
    activity: [
      { ts: daysAgo(1), actor: "system", message: "835 ERA parsed — fully balanced to estimate." },
    ],
    lines: [
      {
        id: "L1", product: "CGM Monitor", hcpcs: "A4238", modifiers: ["NU"],
        units: 1, charge: 800, estPay: 400, primaryPaid: 360, allowed: 400,
        deductible: 0, coinsurance: 40, copay: 0, patientResponsibility: 40,
        carc: ["45"], rarc: [], adjustmentReasons: ["Contractual adjustment"],
        remarkText: [], denialAnalysis: null,
        coAmount: 400, prAmount: 40, oaAmount: 0, piAmount: 0,
      },
      {
        id: "L2", product: "CGM Sensors", hcpcs: "A4239", modifiers: [],
        units: 4, charge: 320, estPay: 200, primaryPaid: 180, allowed: 200,
        deductible: 0, coinsurance: 20, copay: 0, patientResponsibility: 20,
        carc: ["45"], rarc: [], adjustmentReasons: ["Contractual adjustment"],
        remarkText: [], denialAnalysis: null,
        coAmount: 120, prAmount: 20, oaAmount: 0, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10049",
    mondayItemId: "1234567897",
    patientName: "Marcus Thompson",
    dob: "1972-09-18",
    dos: daysAgo(35),
    primaryPayor: "Cigna",
    insuranceType: "Commercial PPO",
    memberId: "CIG556677",
    claimSentDate: daysAgo(32),
    primaryStatus: "Outstanding",
    status277: "Payer Accepted",
    claimStatusCategory: "Denied",
    claimStatusDetail: "Service not covered under member's plan",
    lastClaimStatusCheck: daysAgo(1),
    claimId: "CLM-77888",
    payerClaimNumber: "CIG-33215",
    estPay: 1250,
    primaryPaid: 0,
    prAmount: 0,
    rawEraDate: null,
    primaryPaidDate: null,
    denialAction: null,
    nextActionDate: null,
    lines: [
      {
        id: "L1", product: "CGM Sensors", hcpcs: "A4239", modifiers: ["NU"],
        units: 1, charge: 2200, estPay: 1250, primaryPaid: 0, allowed: 0,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: [], rarc: [], adjustmentReasons: [], remarkText: [],
        denialAnalysis: null, coAmount: 0, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
    ],
  },
  {
    id: "C-10050",
    mondayItemId: "1234567898",
    patientName: "Olivia Martinez",
    dob: "1982-04-17",
    dos: daysAgo(35),
    primaryPayor: "Blue Cross Blue Shield",
    insuranceType: "Commercial PPO",
    memberId: "BCBS554433",
    claimSentDate: daysAgo(33),
    primaryStatus: "Paid",
    status277: "Payer Accepted",
    claimStatusCategory: "Paid",
    claimStatusDetail: "Finalized — payment made",
    lastClaimStatusCheck: daysAgo(10),
    claimId: "CLM-77899",
    payerClaimNumber: "BCBS2026-554433",
    estPay: 1480,
    primaryPaid: 1480,
    prAmount: 0,
    rawEraDate: daysAgo(10),
    rawEraClaimStatus: "Processed as Primary",
    primaryPaidDate: daysAgo(8),
    secondaryPayer: null,
    denialAction: null,
    nextActionDate: null,
    transfer: "Done",
    subscriptionClearance: "Clear",
    claimsHoldReason: null,
    sourceSubscriptionItemId: "SUB-44218",
    sourceOrderItemId: "ORD-99820",
    activity: [
      { ts: daysAgo(33), actor: "system", message: "837 submitted to Stedi." },
      { ts: daysAgo(32), actor: "system", message: "277 Payer Accepted." },
      { ts: daysAgo(10), actor: "system", message: "835 ERA parsed — Paid in full." },
      { ts: daysAgo(8), actor: "system", message: "EFT received — $1,480.00." },
    ],
    lines: [
      {
        id: "L1", product: "Insulin Pump", hcpcs: "E0784", modifiers: ["NU"],
        units: 1, charge: 4500, estPay: 1100, primaryPaid: 1100, allowed: 1100,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: ["45"], rarc: [], adjustmentReasons: ["Contractual adjustment"],
        remarkText: [], denialAnalysis: null,
        coAmount: 3400, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
      {
        id: "L2", product: "CGM Sensors", hcpcs: "A4239", modifiers: ["NU"],
        units: 4, charge: 600, estPay: 280, primaryPaid: 280, allowed: 280,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: ["45"], rarc: [], adjustmentReasons: ["Contractual adjustment"],
        remarkText: [], denialAnalysis: null,
        coAmount: 320, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
      {
        id: "L3", product: "Infusion Set", hcpcs: "A4230", modifiers: ["NU"],
        units: 10, charge: 350, estPay: 100, primaryPaid: 100, allowed: 100,
        deductible: 0, coinsurance: 0, copay: 0, patientResponsibility: 0,
        carc: ["45"], rarc: [], adjustmentReasons: ["Contractual adjustment"],
        remarkText: [], denialAnalysis: null,
        coAmount: 250, prAmount: 0, oaAmount: 0, piAmount: 0,
      },
    ],
  },
];

export function getClaim(id: string): Claim | undefined {
  return MOCK_CLAIMS.find((c) => c.id === id);
}
